import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { addMonths, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameMonth, parseISO, startOfMonth, startOfWeek, subMonths } from 'date-fns'
import { db, clearAllData, ensureDay, getDishesSorted } from './db'
import { displayDate, previousDates, shiftDate, toLocalDate } from './date'
import { calculateCombination, calculateInsight, validDayCount, type Factor, type InsightInput } from './insights'
import { compressPhoto } from './photos'
import { createBackupPayload, exportComplete, exportJson, parseBackup, restoreBackup, saveBlob } from './backup'
import { formatBytes, getStorageState, isStandalone, requestPersistentStorage, type StorageState } from './storage'
import type { AcneLocation, AcneStatus, MealStatus, PhotoKind, Severity } from './types'

type Tab = 'today'|'calendar'|'insights'|'me'
const labels = { chin:'下巴',jawline:'下颌线',leftCheek:'左脸颊',rightCheek:'右脸颊',forehead:'额头',nose:'鼻周',other:'其他',lump:'硬块',inflamed:'红肿',pustule:'白脓',popped:'已挤破',healing:'修复中',recovered:'已恢复' } as const
const mealLabels = {unknown:'未记录',skipped:'没吃',home:'自己做',delivery:'外卖',dineout:'外食'}
const factorLabels: Record<Factor,string> = {milkTea:'奶茶',coffee:'咖啡',icedCoffee:'冰咖啡',hotCoffee:'热咖啡',milkCoffee:'加奶咖啡',blackCoffee:'不加奶咖啡',coldDrink:'冷饮',heavy:'高油重口',delivery:'外卖',dineout:'外食',home:'自己做',period:'经期中',prePeriod:'经期前7天'}
const now = () => Date.now()
const uid = () => crypto.randomUUID()

function App() {
  const settings = useLiveQuery(async()=>await db.appSettings.get('settings') ?? null,[])
  const [tab,setTab]=useState<Tab>('today'), [selectedDate,setSelectedDate]=useState(toLocalDate()), [sheet,setSheet]=useState<ReactNode>(null), [toast,setToast]=useState(''), [update,setUpdate]=useState(false)
  useEffect(()=>{ const handler=()=>setUpdate(true); addEventListener('pwa-update-ready',handler); return()=>removeEventListener('pwa-update-ready',handler)},[])
  useEffect(()=>{ if(!settings || settings.persistAttempted) return; requestPersistentStorage().finally(()=>db.appSettings.update('settings',{persistAttempted:true})) },[settings])
  useEffect(()=>{ if(!settings || settings.standalonePersistAttempted || !isStandalone()) return; requestPersistentStorage().finally(()=>db.appSettings.update('settings',{standalonePersistAttempted:true})) },[settings])
  const showToast=(message:string)=>{setToast(message);setTimeout(()=>setToast(''),2600)}
  if (settings === undefined) return <div className="splash"><Brand/><p>正在打开本地记录…</p></div>
  if (!settings?.onboardingComplete) return <Onboarding onDone={()=>showToast('准备好了，开始记录吧')}/>
  return <div className="app-shell">
    <main>{tab==='today'?<Today date={selectedDate} open={setSheet} toast={showToast}/>:tab==='calendar'?<Calendar openDate={d=>{setSelectedDate(d);setSheet(<DayDetail date={d} open={setSheet} toast={showToast}/>)}}/>:tab==='insights'?<Insights/>:<Me open={setSheet} toast={showToast}/>}</main>
    <nav className="tabbar" aria-label="主导航">{([['today','⌂','今日'],['calendar','▦','日历'],['insights','◉','洞察'],['me','●','我的']] as const).map(([id,icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{icon}</span>{label}</button>)}</nav>
    {sheet&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setSheet(null)}><section className="sheet"><div className="grab"/><button className="close" onClick={()=>setSheet(null)} aria-label="关闭">×</button>{sheet}</section></div>}
    {toast&&<div className="toast">{toast}</div>}
    {update&&<button className="update-toast" onClick={()=>location.reload()}>发现新版本 · 点此刷新</button>}
  </div>
}

function Brand(){return <div className="brand"><div className="brand-icon">😣</div><div><h1>谁惹痘</h1><p>记下每天吃了什么，看看是谁在惹痘。</p></div></div>}
function Onboarding({onDone}:{onDone:()=>void}) {
  const [step,setStep]=useState(0), [baseline,setBaseline]=useState<Record<AcneLocation,number>>({chin:0,jawline:0,leftCheek:0,rightCheek:0,forehead:0,nose:0,other:0}), [baselineStatus,setBaselineStatus]=useState<Record<AcneLocation,Exclude<AcneStatus,'recovered'>>>({chin:'inflamed',jawline:'inflamed',leftCheek:'inflamed',rightCheek:'inflamed',forehead:'inflamed',nose:'inflamed',other:'inflamed'}), [period,setPeriod]=useState(false), [periodStart,setPeriodStart]=useState(toLocalDate())
  const finish=async()=>{const createdAt=now();await db.transaction('rw',[db.appSettings,db.acneBatches,db.acneLesions,db.acneStatusHistory,db.periods],async()=>{await db.appSettings.put({id:'settings',onboardingComplete:true,periodTracking:period,persistAttempted:false,standalonePersistAttempted:false,createdAt});for(const [location,count] of Object.entries(baseline) as [AcneLocation,number][])if(count){const status=baselineStatus[location],batchId=uid();await db.acneBatches.add({id:batchId,localDate:toLocalDate(),location,count,initialStatus:status,severity:'medium',isBaseline:true,createdAt});for(let i=0;i<count;i++){const id=uid();await db.acneLesions.add({id,batchId,createdDate:toLocalDate(),location,currentStatus:status,severity:'medium',isBaseline:true});await db.acneStatusHistory.add({lesionId:id,localDate:toLocalDate(),status,createdAt})}}if(period)await db.periods.add({startDate:periodStart,createdAt})});onDone()}
  return <div className="onboarding">{step===0?<><Brand/><div className="privacy-pill">🔒 所有数据仅保存在你的设备本地</div><button className="primary" onClick={()=>setStep(1)}>开始记录</button></>:step===1?<><h1>现在脸上有哪些痘？</h1><p className="muted">这是初始皮肤基线，不会计入今天新增。</p><div className="card list">{(Object.keys(baseline) as AcneLocation[]).map(k=><div className="baseline-row" key={k}><b>{labels[k]}</b><Stepper value={baseline[k]} onChange={v=>setBaseline({...baseline,[k]:v})}/>{baseline[k]>0&&<select value={baselineStatus[k]} onChange={e=>setBaselineStatus({...baselineStatus,[k]:e.target.value as Exclude<AcneStatus,'recovered'>})}>{(['lump','inflamed','pustule','popped','healing'] as const).map(s=><option key={s} value={s}>{labels[s]}</option>)}</select>}</div>)}</div><button className="primary" onClick={()=>setStep(2)}>继续</button></>:<><h1>是否记录经期？</h1><div className="choice-row"><button className={!period?'selected':''} onClick={()=>setPeriod(false)}>暂时跳过</button><button className={period?'selected':''} onClick={()=>setPeriod(true)}>需要</button></div>{period&&<label className="field">如果正在经期，开始日期<input type="date" value={periodStart} onChange={e=>setPeriodStart(e.target.value)}/></label>}<button className="primary" onClick={finish}>完成设置</button></>}</div>
}

function Today({date,open,toast}:{date:string;open:(n:ReactNode)=>void;toast:(s:string)=>void}){
  const day=useLiveQuery(()=>db.dayRecords.get(date),[date]), drinks=useLiveQuery(()=>db.drinks.where('localDate').equals(date).toArray(),[date])||[], meals=useLiveQuery(()=>db.meals.where('localDate').equals(date).toArray(),[date])||[], dishes=useLiveQuery(()=>db.dishes.toArray())||[], acne=useLiveQuery(()=>db.acneBatches.where('localDate').equals(date).filter(x=>!x.isBaseline).toArray(),[date])||[], lesions=useLiveQuery(()=>db.acneLesions.where('createdDate').equals(date).filter(x=>!x.isBaseline).toArray(),[date])||[], period=useLiveQuery(()=>db.periods.filter(p=>p.startDate<=date&&(!p.endDate||p.endDate>=date)).first(),[date])
  const acneGroups=Object.values(lesions.reduce<Record<string,{location:AcneLocation;status:AcneStatus;count:number}>>((groups,lesion)=>{const key=`${lesion.location}:${lesion.currentStatus}`;groups[key]??={location:lesion.location,status:lesion.currentStatus,count:0};groups[key].count++;return groups},{}))
  const addDrink=async(type:'coffee'|'milkTea'|'other', extra:Record<string,unknown>={})=>{await ensureDay(date);await db.drinks.add({localDate:date,type,createdAt:now(),...extra});await db.dayRecords.update(date,{drinkStatus:'completed',updatedAt:now()});toast('已记录饮品')}
  const noDrinks=async()=>{await ensureDay(date);await db.dayRecords.update(date,{drinkStatus:'completed',updatedAt:now()});toast('已记录：今天没喝这些')}
  return <div className="page"><Header title="今天" subtitle={displayDate(date)}/>
    <Card title="🥤 饮品" action={<button className="link" onClick={()=>open(<DrinkSheet add={addDrink}/>)}>添加</button>}><div className="chips">{drinks.map((d,i)=><span key={i}>{d.type==='coffee'?'☕ 咖啡':d.type==='milkTea'?'🧋 奶茶':`🥤 ${d.name||'其他'}`}</span>)}</div>{!drinks.length&&day?.drinkStatus!=='completed'&&<p className="muted">还没有记录</p>}<div className="button-row"><button onClick={()=>addDrink('coffee',{temperature:'hot',milk:true})}>☕ 咖啡</button><button onClick={()=>addDrink('milkTea')}>🧋 奶茶</button><button onClick={()=>open(<DrinkSheet add={addDrink}/>)}>🥤 其他</button></div><button className="outline full" onClick={noDrinks}>今天没喝这些</button></Card>
    <Card title="🍴 三餐">{(['breakfast','lunch','dinner'] as const).map(kind=>{const meal=meals.find(m=>m.meal===kind),names=meal?.dishIds.map(id=>dishes.find(d=>d.id===id)?.name).filter(Boolean).join('、');return <button className="meal-row" key={kind} onClick={()=>open(<MealSheet date={date} meal={kind} toast={toast}/>)}><span>{kind==='breakfast'?'早餐':kind==='lunch'?'午餐':'晚餐'}</span><span className={meal?.status==='unknown'||!meal?'muted':''}>{mealLabels[meal?.status||'unknown']}{names?` · ${names}`:''}{meal?.heavy?' · 🔥':''} ›</span></button>})}</Card>
    <Card title="🔴 今日痘痘"><p className="muted">{day?.acneStatus==='completed'?acne.length?`今天新增 ${acne.reduce((s,a)=>s+a.count,0)} 颗`:'今天没有新增':'今天有新长痘吗？'}</p>{acneGroups.map(group=><div className="record" key={`${group.location}:${group.status}`}>{labels[group.location]} · {labels[group.status]} · {group.count}颗</div>)}<div className="button-row"><button onClick={async()=>{await ensureDay(date);await db.dayRecords.update(date,{acneStatus:'completed',updatedAt:now()});toast('已记录：没有新增')}}>没有新增</button><button className="accent" onClick={()=>open(<AcneSheet date={date} toast={toast}/>)}>＋ 有新增</button></div><label className="outline full file-button">📷 记录今日皮肤<input hidden type="file" accept="image/*" capture="user" onChange={e=>savePhoto(e,date,'skin',undefined,toast)}/></label></Card>
    <Card title="🩸 经期" action={<button className="link" onClick={()=>open(<PeriodSheet date={date} toast={toast}/>)}>{period?'经期中':'记录'}</button>}><p className="muted">{period?`${period.startDate} 开始`:'当前未在经期'}</p></Card>
  </div>
}

function DrinkSheet({add}:{add:(t:'coffee'|'milkTea'|'other',x?:Record<string,unknown>)=>void}){const [type,setType]=useState<'coffee'|'milkTea'|'other'>('coffee'),[temp,setTemp]=useState<'iced'|'hot'|'room'>('hot'),[milk,setMilk]=useState(true),[otherType,setOtherType]=useState<'cola'|'soda'|'juice'|'other'>('cola'),[name,setName]=useState('');return <div><h2>添加饮品</h2><Segment options={[['coffee','咖啡'],['milkTea','奶茶'],['other','其他']]} value={type} set={v=>setType(v as typeof type)}/>{type!=='milkTea'&&<><p className="label">温度</p><Segment options={type==='coffee'?[['iced','冰'],['hot','热']]:[['iced','冰'],['room','常温']]} value={temp} set={v=>setTemp(v as typeof temp)}/></>}{type==='coffee'&&<><p className="label">是否加奶</p><Segment options={[[true,'加奶'],[false,'不加奶']]} value={milk} set={v=>setMilk(v as boolean)}/></>}{type==='other'&&<><label className="field">饮料类型<select value={otherType} onChange={e=>setOtherType(e.target.value as typeof otherType)}><option value="cola">可乐</option><option value="soda">苏打水</option><option value="juice">果汁</option><option value="other">其他</option></select></label>{otherType==='other'&&<label className="field">名称（可选）<input value={name} onChange={e=>setName(e.target.value)} placeholder="例：柠檬茶"/></label>}</>}<button className="primary" onClick={()=>add(type,type==='coffee'?{temperature:temp,milk}:type==='other'?{temperature:temp,otherType,name}:undefined)}>立即记录</button></div>}
function MealSheet({date,meal,toast}:{date:string;meal:'breakfast'|'lunch'|'dinner';toast:(s:string)=>void}) {
  const existing=useLiveQuery(()=>db.meals.where('[localDate+meal]').equals([date,meal]).first(),[date,meal])
  const dishes=useLiveQuery(()=>getDishesSorted())||[]
  const [status,setStatus]=useState<MealStatus>('home'),[heavy,setHeavy]=useState(false),[dishIds,setDishIds]=useState<number[]>([])
  useEffect(()=>{if(!existing)return;setStatus(existing.status);setHeavy(existing.heavy);setDishIds(existing.dishIds)},[existing])
  const save=async()=>{
    const current=await db.meals.where('[localDate+meal]').equals([date,meal]).first()
    const selectedIds=status==='home'?dishIds:[]
    const value={localDate:date,meal,status,heavy:status==='home'?dishes.filter(d=>d.id&&selectedIds.includes(d.id)).some(d=>d.heavy):(status==='delivery'||status==='dineout')&&heavy,dishIds:selectedIds,createdAt:current?.createdAt||now(),updatedAt:now()}
    const previousIds=current?.status==='home'?current.dishIds:[],added=selectedIds.filter(id=>!previousIds.includes(id)),removed=previousIds.filter(id=>!selectedIds.includes(id))
    await db.transaction('rw',[db.meals,db.dishes,db.dayRecords],async()=>{
      if(current?.id)await db.meals.update(current.id,value);else await db.meals.add(value)
      for(const id of added){const dish=await db.dishes.get(id);if(dish)await db.dishes.update(id,{eatCount:dish.eatCount+1,lastEatenDate:date})}
      for(const id of removed){const dish=await db.dishes.get(id);if(dish)await db.dishes.update(id,{eatCount:Math.max(0,dish.eatCount-1)})}
      await ensureDay(date)
    })
    toast(current?'三餐记录已更新':'三餐已保存')
  }
  return <div><h2>{existing?'编辑':'记录'}{meal==='breakfast'?'早餐':meal==='lunch'?'午餐':'晚餐'}</h2><div className="choice-grid">{(['skipped','home','delivery','dineout'] as MealStatus[]).map(v=><button className={status===v?'selected':''} onClick={()=>setStatus(v)} key={v}>{mealLabels[v]}</button>)}</div>{status==='home'&&<><SectionTitle>选择菜品（可多选）</SectionTitle>{dishes.length?dishes.map(d=><label className="toggle" key={d.id}><span>{d.name}{d.heavy?' · 🔥':''}</span><input type="checkbox" checked={Boolean(d.id&&dishIds.includes(d.id))} onChange={()=>d.id&&setDishIds(ids=>ids.includes(d.id!)?ids.filter(x=>x!==d.id):[...ids,d.id!])}/></label>):<p className="muted">请先到“我的菜单”添加常吃菜品；也可以直接保存。</p>}</>}{(status==='delivery'||status==='dineout')&&<label className="toggle"><span>🔥 高油重口</span><input type="checkbox" checked={heavy} onChange={e=>setHeavy(e.target.checked)}/></label>}<button className="primary" onClick={save}>{existing?'更新记录':'保存'}</button></div>
}
function AcneSheet({date,toast}:{date:string;toast:(s:string)=>void}){const [location,setLocation]=useState<AcneLocation>('chin'),[count,setCount]=useState(1),[statuses,setStatuses]=useState<Exclude<AcneStatus,'recovered'>[]>(['inflamed']),[severity,setSeverity]=useState<Severity>('medium'),[photo,setPhoto]=useState<File>();useEffect(()=>setStatuses(current=>Array.from({length:count},(_,index)=>current[index]??'inflamed')),[count]);const save=async()=>{const id=uid(),createdAt=now();await db.transaction('rw',[db.acneBatches,db.acneLesions,db.acneStatusHistory,db.dayRecords],async()=>{await db.acneBatches.add({id,localDate:date,location,count,initialStatus:statuses[0]||'inflamed',severity,isBaseline:false,createdAt});for(let i=0;i<count;i++){const status=statuses[i]||'inflamed',lesionId=uid();await db.acneLesions.add({id:lesionId,batchId:id,createdDate:date,location,currentStatus:status,severity,isBaseline:false});await db.acneStatusHistory.add({lesionId,localDate:date,status,createdAt})}await ensureDay(date);await db.dayRecords.update(date,{acneStatus:'completed',updatedAt:now()})});toast(`已分别记录 ${count} 颗新增痘痘`);if(photo)try{await storePhoto(photo,date,'lesion',id)}catch{toast('痘痘已保存，但照片处理失败')}};return <div><h2>新增痘痘</h2><label className="field">部位<select value={location} onChange={e=>setLocation(e.target.value as AcneLocation)}>{(Object.keys(labels) as string[]).slice(0,7).map(k=><option key={k} value={k}>{labels[k as AcneLocation]}</option>)}</select></label><div className="field"><span>数量</span><Stepper value={count} onChange={value=>setCount(Math.max(1,value))}/></div><p className="label">每颗痘痘的当前状态</p><div className="lesion-statuses">{statuses.map((status,index)=><label key={index}><span>第 {index+1} 颗</span><select value={status} onChange={e=>setStatuses(current=>current.map((item,i)=>i===index?e.target.value as Exclude<AcneStatus,'recovered'>:item))}>{(['lump','inflamed','pustule','popped','healing'] as const).map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label>)}</div><p className="label">程度</p><Segment options={[['mild','轻微'],['medium','中等'],['severe','严重']]} value={severity} set={v=>setSeverity(v as Severity)}/><label className="outline full file-button">📷 添加照片<input hidden type="file" accept="image/*" capture="user" onChange={e=>setPhoto(e.target.files?.[0])}/></label><button className="primary" onClick={save}>保存</button></div>}
async function storePhoto(file:File,date:string,kind:PhotoKind,ownerId?:string){const result=await compressPhoto(file);const id=uid();await db.photos.add({id,kind,localDate:date,blob:result.blob,mimeType:result.blob.type,width:result.width,height:result.height,createdAt:now(),ownerId});return id}
async function savePhoto(e:React.ChangeEvent<HTMLInputElement>,date:string,kind:PhotoKind,ownerId:string|undefined,toast:(s:string)=>void){const file=e.target.files?.[0];if(!file)return;try{await storePhoto(file,date,kind,ownerId);toast('照片已保存在本机')}catch{toast('照片处理失败，请重试')}}
function PeriodSheet({date,toast}:{date:string;toast:(s:string)=>void}){const [start,setStart]=useState(date);return <div><h2>记录经期</h2><label className="field">月经开始日期<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><button className="primary" onClick={async()=>{await db.periods.add({startDate:start,createdAt:now()});toast('经期开始已记录')}}>记录开始</button><button className="outline full" onClick={async()=>{const current=await db.periods.filter(p=>p.startDate<=date&&!p.endDate).last();if(current?.id)await db.periods.update(current.id,{endDate:date});toast('经期结束已记录')}}>记录今天结束</button></div>}

function Calendar({openDate}:{openDate:(d:string)=>void}) {
  const [cursor,setCursor]=useState(startOfMonth(new Date()))
  const from=format(startOfWeek(startOfMonth(cursor),{weekStartsOn:0}),'yyyy-MM-dd'),to=format(endOfWeek(endOfMonth(cursor),{weekStartsOn:0}),'yyyy-MM-dd')
  const data=useLiveQuery(async()=>({drinks:await db.drinks.where('localDate').between(from,to,true,true).toArray(),meals:await db.meals.where('localDate').between(from,to,true,true).toArray(),acne:await db.acneBatches.where('localDate').between(from,to,true,true).toArray(),periods:await db.periods.toArray()}),[from,to])
  const dates=eachDayOfInterval({start:parseISO(from),end:parseISO(to)})
  return <div className="page"><Header title="日历"/><div className="calendar-head"><button onClick={()=>setCursor(subMonths(cursor,1))}>‹</button><b>{format(cursor,'yyyy年M月')}</b><button onClick={()=>setCursor(addMonths(cursor,1))}>›</button></div><div className="weekdays">{['日','一','二','三','四','五','六'].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{dates.map(date=>{const d=format(date,'yyyy-MM-dd'), drinks=data?.drinks.filter(x=>x.localDate===d)||[], meals=data?.meals.filter(x=>x.localDate===d)||[], acne=(data?.acne||[]).filter(x=>x.localDate===d&&!x.isBaseline).reduce((s,x)=>s+x.count,0), inPeriod=data?.periods.some(p=>p.startDate<=d&&(!p.endDate||p.endDate>=d));const marks=[acne?`🔴+${acne}`:'',inPeriod?'🩸':'',drinks.some(x=>x.type==='milkTea')?'🧋':'',meals.some(x=>x.heavy)?'🔥':'',drinks.some(x=>x.type==='coffee')?'☕':'',drinks.some(x=>x.temperature==='iced'&&x.type!=='milkTea')?'❄️':''].filter(Boolean).slice(0,3);return <button className={`day-cell ${!isSameMonth(date,cursor)?'outside':''} ${d===toLocalDate()?'today':''}`} key={d} onClick={()=>openDate(d)}><span>{format(date,'d')}</span><small>{marks.join(' ')}</small></button>})}</div></div>
}

function DayDetail({date,open,toast}:{date:string;open:(n:ReactNode)=>void;toast:(s:string)=>void}) {
  const data=useLiveQuery(async()=>({day:await db.dayRecords.get(date),drinks:await db.drinks.where('localDate').equals(date).toArray(),meals:await db.meals.where('localDate').equals(date).toArray(),dishes:await db.dishes.toArray(),acne:await db.acneBatches.where('localDate').equals(date).toArray(),photos:await db.photos.where('localDate').equals(date).toArray(),period:await db.periods.filter(p=>p.startDate<=date&&(!p.endDate||p.endDate>=date)).first()}),[date])
  const [timeline,setTimeline]=useState(false)
  return <div><h2>{displayDate(date)}</h2><SectionTitle>新增痘痘</SectionTitle>{data?.day?.acneStatus==='completed'?<p>{data.acne.filter(x=>!x.isBaseline).reduce((s,x)=>s+x.count,0)} 颗</p>:<p className="muted">未记录</p>}<button className="outline" onClick={()=>open(<AcneSheet date={date} toast={toast}/>)}>补录新增</button><SectionTitle>饮品</SectionTitle><p>{data?.day?.drinkStatus==='completed'?(data.drinks.length?data.drinks.map(x=>x.type==='coffee'?'咖啡':x.type==='milkTea'?'奶茶':x.name||'其他').join('、'):'明确没有饮用'):'未记录'}</p><SectionTitle>三餐</SectionTitle>{(['breakfast','lunch','dinner'] as const).map(m=>{const record=data?.meals.find(x=>x.meal===m),names=record?.dishIds.map(id=>data?.dishes.find(d=>d.id===id)?.name).filter(Boolean).join('、');return <button className="meal-row" key={m} onClick={()=>open(<MealSheet date={date} meal={m} toast={toast}/>)}><span>{m==='breakfast'?'早餐':m==='lunch'?'午餐':'晚餐'}</span><span className={!record?'muted':''}>{mealLabels[record?.status||'unknown']}{names?` · ${names}`:''}{record?.heavy?' · 🔥':''} ›</span></button>})}<SectionTitle>经期与照片</SectionTitle><p>{data?.period?'经期中':'非经期'} · {data?.photos.length||0} 张照片</p><button className="outline full" onClick={()=>setTimeline(!timeline)}>{timeline?'收起':'查看前3天'}</button>{timeline&&<Timeline date={date}/>}<button className="danger-link" onClick={async()=>{if(confirm(`删除 ${date} 的全部记录？`)){await db.transaction('rw',[db.dayRecords,db.drinks,db.meals,db.acneBatches,db.acneLesions,db.acneStatusHistory,db.photos],async()=>{const batches=await db.acneBatches.where('localDate').equals(date).toArray();const ids=batches.map(x=>x.id);const lesions=await db.acneLesions.where('batchId').anyOf(ids).toArray();await db.acneStatusHistory.where('lesionId').anyOf(lesions.map(x=>x.id)).delete();await db.acneLesions.where('batchId').anyOf(ids).delete();await db.acneBatches.where('localDate').equals(date).delete();await db.drinks.where('localDate').equals(date).delete();await db.meals.where('localDate').equals(date).delete();await db.photos.where('localDate').equals(date).delete();await db.dayRecords.delete(date)});toast('当日记录已删除')}}}>删除这一天的记录</button></div>
}
function Timeline({date}:{date:string}){const dates=[...previousDates(date,3),date];const data=useLiveQuery(async()=>({drinks:await db.drinks.where('localDate').anyOf(dates).toArray(),meals:await db.meals.where('localDate').anyOf(dates).toArray(),acne:await db.acneBatches.where('localDate').anyOf(dates).toArray()}),[date]);return <div className="timeline">{dates.map((d,i)=>{const icons=[data?.drinks.some(x=>x.localDate===d&&x.type==='milkTea')?'🧋':'',data?.drinks.some(x=>x.localDate===d&&x.type==='coffee')?'☕':'',data?.meals.some(x=>x.localDate===d&&x.heavy)?'🔥':'',data?.acne.some(x=>x.localDate===d&&!x.isBaseline)?'🔴':''].filter(Boolean);return <div key={d}><b>{i===3?'当天':`t-${3-i}`}</b><span>{icons.join(' ')||'—'}</span></div>})}</div>}

function Insights(){const data=useLiveQuery(async()=>({days:await db.dayRecords.toArray(),drinks:await db.drinks.toArray(),meals:await db.meals.toArray(),acne:await db.acneBatches.toArray(),periods:await db.periods.toArray()}),[]) as InsightInput|undefined;const valid=data?validDayCount(data):0;const factors:Factor[]=['milkTea','coffee','icedCoffee','hotCoffee','milkCoffee','blackCoffee','coldDrink','heavy','delivery','dineout','home','period','prePeriod'];const insights=data?factors.map(f=>calculateInsight(f,data)):[];const combo=data?calculateCombination(['milkTea','heavy'],data):undefined;const since=shiftDate(toLocalDate(),-29);const locations=data?.acne.filter(x=>!x.isBaseline&&x.localDate>=since).reduce<Record<string,number>>((acc,x)=>{acc[x.location]=(acc[x.location]||0)+x.count;return acc},{})||{};const max=Math.max(1,...Object.values(locations));return <div className="page"><Header title="洞察" subtitle="基于你的记录，发现可能的个人时间关联"/>{valid<14?<Card title="还在收集线索"><div className="progress"><span style={{width:`${Math.min(100,valid/14*100)}%`}}/></div><h2>{valid} / 14天</h2><p className="muted">饮品、三餐和当天新增痘痘都明确记录，才算一个有效记录日。</p></Card>:<>{insights.map(x=><Card key={x.factor} title={factorLabels[x.factor]} action={<span className={`badge ${x.level==='数据不足'?'neutral':''}`}>{x.level}</span>}><p className="muted">完整暴露窗口 {x.exposureCount} 次 · 对照 {x.controlCount} 次</p>{x.level!=='数据不足'&&<div className="metrics"><div><b>{x.exposureOccurrence.toFixed(0)}%</b><span>72小时有新增</span></div><div><b>{x.averageAcneCount.toFixed(1)}</b><span>平均新增</span></div><div><b>{x.mainOffset==null?'—':`+${x.mainOffset}天`}</b><span>主要时点</span></div></div>}<p className="fine">这是个人观察性启发式结果，不是医学结论。</p></Card>)}{combo&&combo.exposureCount>=5&&combo.controlCount>=5&&<Card title="奶茶 + 高油重口" action={<span className="badge">{combo.level}</span>}><p className="muted">组合完整窗口 {combo.exposureCount} 次 · 对照 {combo.controlCount} 次</p><p className="fine">组合观察仅在两组样本均足够时展示，不代表因果。</p></Card>}</>}<Card title="最近长在哪里？" action={<span className="muted">近30天</span>}>{(Object.keys(labels) as AcneLocation[]).map(k=><div className="bar-row" key={k}><span>{labels[k]}</span><i><em style={{width:`${(locations[k]||0)/max*100}%`}}/></i><b>{locations[k]||0}</b></div>)}</Card></div>}

function Me({open,toast}:{open:(n:ReactNode)=>void;toast:(s:string)=>void}){const active=useLiveQuery(()=>db.acneLesions.where('currentStatus').notEqual('recovered').count())||0,photos=useLiveQuery(()=>db.photos.count())||0;return <div className="page"><Header title="我的"/><Group title="记录"><Menu icon="🍳" title="我的菜单" subtitle="常吃与最近吃过" onClick={()=>open(<DishManager toast={toast}/>)}/><Menu icon="🔴" title="活跃痘痘" subtitle={`当前 ${active} 颗`} onClick={()=>open(<ActiveAcne toast={toast}/>)}/><Menu icon="🩸" title="经期记录" subtitle="查看历史" onClick={()=>open(<PeriodHistory/>)}/><Menu icon="📷" title="皮肤照片" subtitle={`共 ${photos} 张`} onClick={()=>open(<PhotoGallery/>)}/></Group><Group title="数据"><Menu icon="🛡️" title="数据安全" subtitle="存储状态与数据清理" onClick={()=>open(<DataSafety toast={toast}/>)}/><Menu icon="📦" title="数据备份" subtitle="导出与恢复" onClick={()=>open(<BackupPage toast={toast}/>)}/></Group><Group title="关于"><Menu icon="ℹ️" title="关于谁惹痘" subtitle="版本 1.0 · 仅供个人观察" onClick={()=>open(<About/>)}/></Group><div className="privacy-note">所有数据仅保存在你的设备本地<br/>保护隐私，安心记录 ❤️</div></div>}

function DishManager({toast}:{toast:(s:string)=>void}){const dishes=useLiveQuery(()=>getDishesSorted())||[], [name,setName]=useState(''),[heavy,setHeavy]=useState(false),[photo,setPhoto]=useState<File>();return <div><h2>我的菜单</h2><label className="field">菜名<input value={name} onChange={e=>setName(e.target.value)} placeholder="例：番茄炒蛋"/></label><label className="toggle"><span>🔥 高油重口</span><input type="checkbox" checked={heavy} onChange={e=>setHeavy(e.target.checked)}/></label><label className="outline full file-button">📷 菜品照片（可选）<input hidden type="file" accept="image/*" onChange={e=>setPhoto(e.target.files?.[0])}/></label><button className="primary" disabled={!name.trim()} onClick={async()=>{const id=await db.dishes.add({name:name.trim(),heavy,eatCount:0,createdAt:now()});setName('');toast('菜品已添加');if(photo)try{const photoId=await storePhoto(photo,toLocalDate(),'dish',String(id));await db.dishes.update(id,{photoId});setPhoto(undefined)}catch{toast('菜品已保存，但照片处理失败')}}}>添加菜品</button><SectionTitle>全部菜品</SectionTitle>{dishes.length?dishes.map(d=><div className="row" key={d.id}><div><b>{d.name}</b><small>{d.eatCount} 次{d.heavy?' · 🔥':''}{d.photoId?' · 有照片':''}</small></div><button className="danger-link" onClick={()=>d.id&&db.dishes.delete(d.id)}>删除</button></div>):<p className="muted">还没有菜品</p>}</div>}
function ActiveAcne({toast}:{toast:(s:string)=>void}){const lesions=useLiveQuery(()=>db.acneLesions.where('currentStatus').notEqual('recovered').toArray())||[];const update=async(id:string,status:AcneStatus)=>{await db.transaction('rw',[db.acneLesions,db.acneStatusHistory],async()=>{await db.acneLesions.update(id,{currentStatus:status,...(status==='recovered'?{recoveredDate:toLocalDate()}: {})});await db.acneStatusHistory.add({lesionId:id,localDate:toLocalDate(),status,createdAt:now()})});toast('状态已更新')};return <div><h2>活跃痘痘</h2>{lesions.length?lesions.map(x=><div className="row lesion" key={x.id}><div><b>{labels[x.location]}</b><small>{x.createdDate} · {x.isBaseline?'初始痘痘':'新增痘痘'}</small></div><select value={x.currentStatus} onChange={e=>update(x.id,e.target.value as AcneStatus)}>{(['lump','inflamed','pustule','popped','healing','recovered'] as const).map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div>):<p className="muted">目前没有活跃痘痘</p>}</div>}
function PeriodHistory(){const periods=useLiveQuery(()=>db.periods.reverse().toArray())||[];return <div><h2>经期记录</h2>{periods.map(p=><div className="row" key={p.id}><b>{p.startDate}</b><span>{p.endDate?`至 ${p.endDate}`:'进行中'}</span></div>)}</div>}
function PhotoGallery(){const photos=useLiveQuery(()=>db.photos.reverse().toArray());const urls=useMemo(()=>(photos||[]).map(x=>({id:x.id,url:URL.createObjectURL(x.blob),date:x.localDate})),[photos]);useEffect(()=>()=>urls.forEach(x=>URL.revokeObjectURL(x.url)),[urls]);return <div><h2>皮肤照片</h2><div className="photo-grid">{urls.map(x=><figure key={x.id}><img src={x.url}/><figcaption>{x.date}</figcaption></figure>)}</div>{!urls.length&&<p className="muted">还没有照片</p>}</div>}

function DataSafety({toast}:{toast:(s:string)=>void}){const [state,setState]=useState<StorageState>(), [healthy,setHealthy]=useState<boolean>();const latest=useLiveQuery(()=>db.backupMetadata.where('kind').equals('complete').last());useEffect(()=>{getStorageState().then(setState);db.open().then(()=>setHealthy(true)).catch(()=>setHealthy(false))},[]);return <div><h2>数据安全</h2><div className="status-list"><Status label="本地数据库" value={healthy==null?'检查中':healthy?'正常':'异常'}/><Status label="存储保护" value={!state?'检查中':!state.supported?'当前浏览器不支持':state.persisted?'已获得持久化保护':'本地保存中（未获额外保护）'}/><Status label="当前存储占用" value={formatBytes(state?.usage)}/><Status label="可用配额" value={formatBytes(state?.quota)}/><Status label="最近完整备份" value={latest?format(latest.createdAt,'yyyy年M月d日'):'尚未备份'}/></div>{state?.supported&&!state.persisted&&<button className="primary" onClick={async()=>{const ok=await requestPersistentStorage();setState(await getStorageState());toast(ok?'已获得持久化存储保护':'数据仍会保存在本机，但浏览器暂未授予额外保护')}}>重新申请存储保护</button>}<p className="notice">即使没有获得额外保护，记录仍保存在本机 IndexedDB，可正常关闭、重开和离线使用；但系统在存储压力等情况下仍可能回收网站数据。建议定期导出完整备份。</p><button className="danger-link" onClick={async()=>{if(prompt('此操作无法撤销。请输入“清空”确认')==='清空'){await clearAllData();toast('所有本地数据已清空');location.reload()}}}>清空所有数据</button></div>}
function BackupPage({toast}:{toast:(s:string)=>void}){const input=useRef<HTMLInputElement>(null),[pending,setPending]=useState<{payload:Awaited<ReturnType<typeof createBackupPayload>>;photos:Awaited<ReturnType<typeof parseBackup>>['photos']}|null>(null);const stamp=()=>format(new Date(),'yyyyMMdd-HHmm');return <div><h2>数据备份</h2><p className="muted">数据备份为 JSON，不包含照片。完整备份为 ZIP，包含全部照片。</p><button className="outline full" onClick={async()=>{await saveBlob(await exportJson(),`谁惹痘-数据备份-${stamp()}.json`);await db.backupMetadata.add({kind:'data',createdAt:now(),recordCounts:{}});toast('数据备份已生成')}}>导出数据备份 JSON</button><button className="primary" onClick={async()=>{await saveBlob(await exportComplete(),`谁惹痘-完整备份-${stamp()}.zip`);await db.backupMetadata.add({kind:'complete',createdAt:now(),recordCounts:{}});toast('完整备份已生成')}}>导出完整备份 ZIP</button><p className="notice">完整备份包含皮肤照片，请妥善保存。</p><input ref={input} hidden type="file" accept=".json,.zip,application/json,application/zip" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{setPending(await parseBackup(file));toast('备份校验通过，请确认恢复')}catch(err){toast(err instanceof Error?err.message:'备份校验失败')}}}/><button className="outline full" onClick={()=>input.current?.click()}>选择备份文件恢复</button>{pending&&<div className="confirm-box"><b>备份已通过完整校验</b><p>恢复将替换当前所有数据，无法自动合并。</p><button className="danger" onClick={async()=>{if(confirm('确定替换当前所有数据？')){try{await restoreBackup(pending.payload,pending.photos);toast('恢复完成，记录数量已校验');location.reload()}catch{toast('恢复失败，当前数据库未被部分覆盖')}}}}>确认替换并恢复</button></div>}</div>}
function About(){return <div><Brand/><p>一款仅供个人使用的饮食习惯 × 痘痘变化轻量追踪工具。</p><p className="notice">洞察仅反映个人记录中的时间关联，不构成医学诊断、治疗建议或因果结论。</p><p className="muted">版本 1.0 · 无账号 · 无云同步 · 无分析追踪</p></div>}

function Header({title,subtitle}:{title:string;subtitle?:string}){return <header><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</header>}
function Card({title,action,children}:{title:string;action?:ReactNode;children:ReactNode}){return <section className="card"><div className="card-title"><h2>{title}</h2>{action}</div>{children}</section>}
function Group({title,children}:{title:string;children:ReactNode}){return <section className="group"><h3>{title}</h3><div className="card list">{children}</div></section>}
function Menu({icon,title,subtitle,onClick}:{icon:string;title:string;subtitle:string;onClick:()=>void}){return <button className="menu" onClick={onClick}><span className="menu-icon">{icon}</span><span><b>{title}</b><small>{subtitle}</small></span><i>›</i></button>}
function Status({label,value}:{label:string;value:string}){return <div className="row"><span>{label}</span><b>{value}</b></div>}
function SectionTitle({children}:{children:ReactNode}){return <h3 className="section-title">{children}</h3>}
function Stepper({value,onChange}:{value:number;onChange:(n:number)=>void}){return <div className="stepper"><button onClick={()=>onChange(Math.max(0,value-1))}>−</button><b>{value}</b><button onClick={()=>onChange(value+1)}>＋</button></div>}
function Segment({options,value,set}:{options:[unknown,string][];value:unknown;set:(v:unknown)=>void}){return <div className="segment">{options.map(([v,label])=><button key={String(v)} className={value===v?'selected':''} onClick={()=>set(v)}>{label}</button>)}</div>}

export default App
